### ISSUE TITLE
Dependency conflict - cannot pip install

### ISSUE THREAD

**Issue by robmarkcole** [roboflow-ai/roboflow-python#26]
On Colab:

```
!pip install -q roboflow

.
.
.
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
google-colab 1.0.0 requires requests~=2.23.0, but you have requests 2.27.1 which is incompatible.
datascience 0.10.6 requires folium==0.2.1, but you have folium 0.8.3 which is incompatible.
albumentations 0.1.12 requires imgaug<0.2.7,>=0.2.5, but you have imgaug 0.2.9 which is incompatible.

```

**Comment by mo-traor3-ai** [comment]
The error is due to Colab's preset package dependencies as well as the dependency resolver (as you likely already know) with the pip package and all the other packages necessary to run the model training. The notebook still runs fine, however.

The spot you'll want to continue on to paste your python export code from your dataset is actually the cell below the one with "!pip install -q roboflow"

Example from the [YOLOv5 notebook](https://models.roboflow.com/object-detection/yolov5): 
![image](https://user-images.githubusercontent.com/89935638/160926577-2c1ead39-7471-491d-8aef-982c14e4d72a.png)

The dataset will export just fine in that cell (the one that starts with "%cd /content/yolov5"). You'll just paste everything from "!pip install roboflow" to the rest of the dataset export code right below "%cd /content/yolov5."

**Comment by FrancescoSaverioZuppichini** [comment]
Hi @robmarkcole, are you still having this issue?

**Comment by robmarkcole** [comment]
I was just able to pip install
In a colab instance without issue so this can be closed. Cheers
